### PR TITLE
New blog post: Using Avalon-MM for FPGA-HPS communication

### PR DESCRIPTION
**Pull request by DigitalBrains1**
There are still a few points I'd like to improve:
* First of all, I wish to add a paragraph to the packet-fifo README before I push to master there. Currently, there's *README FIXME link* in the text. Please ignore this. I will fix it before publishing.
* I'd like the image to look a little different. Perhaps a white background, maybe a caption, ability to click to expand to whole browser canvas? Do you guys happen to know the magic incantation for that?
* The syntax highlighting for the terminal output (first code block, starting with `$ ~/intelFPGA/18.1/...`) looks dumb. Do you know how to control syntax highlighting?
* I'm not fond of the need to scroll to the right to see the full ~80 columns of the C code, but perhaps this is a consequence of the desire for uniformity in width of the column (text vs. code). What are your thoughts?
* That would actually be solved for the Device Tree snippet by just omitting the line numbers. Is there a flag to do that?

Those are the things that stood out to me.

Are there any other points that need to be improved before it is good enough to post on the site?

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Impressive work :)

> I'd like the image to look a little different. Perhaps a white background, maybe a caption, ability to click to expand to whole browser canvas? Do you guys happen to know the magic incantation for that?

I know we can do it on the new website (we can mark the SVG as influenceable by CSS and go from there), but I'm very unfamiliar with the current setup. I guess the best you can do is to just add a white square with Inkscape..

> The syntax highlighting for the terminal output (first code block, starting with $ ~/intelFPGA/18.1/...) looks dumb. Do you know how to control syntax highlighting?

This is easy on the new website.. not sure about this one.

> I'm not fond of the need to scroll to the right to see the full ~80 columns of the C code, but perhaps this is a consequence of the desire for uniformity in width of the column (text vs. code). What are your thoughts?

Okay okay, broken record but, the new website has a no-scroll threshold of 90 columns instead.

-----------------------------

Some questions/comments:

* Would it be nice to add a Clash example too? As in, how to use it.
* The introducing links to "https://github.com/DigitalBrains1/packet-fifo" but this gets me a 404. 
* In general, I like linking things like "https://github.com/DigitalBrains1/packet-fifo" as [github.com/DigitalBrains1/packet-fifo](https://github.com/DigitalBrains1/packet-fifo), just so you can see where it's hosted from looking a the link alone.
* edit: should these repos be hosted under [github.com/clash-lang](https://github.com/clash-lang)?

**Comment by DigitalBrains1** [comment]
> Impressive work :)

Thanks! :-)

> * Would it be nice to add a Clash example too? As in, how to use it.

I've purposely left this out because it can be found by perusing the linked project and the question specifically noted the trouble was not at that side but at the HPS side. I think it would add significantly to the length and the time needed to write it. Of course, it depends a bit on at what point you consider it "an example". Like, is just the type of the top entity perhaps an example?

> * The introducing links to "https://github.com/DigitalBrains1/packet-fifo" but this gets me a 404.

Ah yes, it's still private, which is on purpose but I forgot to note it here because the link works fine for me! *Issue closed, works for me*.

> * In general, I like linking things like "https://github.com/DigitalBrains1/packet-fifo" as [github.com/DigitalBrains1/packet-fifo](https://github.com/DigitalBrains1/packet-fifo), just so you can see where it's hosted from looking a the link alone.

I agree, I'll change it.

**Comment by martijnbastiaan** [comment]
> I've purposely left this out because it can be found by perusing the linked project and the question specifically noted the trouble was not at that side but at the HPS side. I think it would add significantly to the length and the time needed to write it. Of course, it depends a bit on at what point you consider it "an example". 

Good point.

> Like, is just the type of the top entity perhaps an example?

Yes, I think that would suffice.

**Comment by DigitalBrains1** [comment]
Changed links:
* functionalprogramming.slack.com
* First mentions of GitHub only
* added " (from terasic.com.tw)" to link to DE-10 manual

Further mentions of GitHub are from context clearly inside the first mentions, would be too verbose IMO.

I think the other links would look bad when expanded. I intepreted your comment as just those links that read easily, like the GitHub ones, is that correct?

**Comment by christiaanb** [comment]
You can get different code formatting options using the

```
~~~haskell

~~~
```
Style code blocks instead of using 4-space indent. I think it's `pygments` based, so you can use their supported languages for automated highlighting. If you just want monospace text you can do:
```
~~~text

~~~
```

**Comment by christiaanb** [comment]
With regards to the 80-column thing. That's just a consequence of the style sheet. You could use 4 or 2 space indent for your C-code so that it fits with the style. Perhaps there is a way to turn off line numbers, I don't know right now.

**Comment by christiaanb** [comment]
And with regard to image background, I think you can add like a `style` part to your `` tag, I think. At least, I thought that's how you do it in html.

**Comment by christiaanb** [comment]
for turning off line number

```
~~~c?line_numbers=false

~~~
```

might work. But if I look at https://github.com/middleman/middleman-syntax you might have to do:

```
<% code("c", :line_numbers => false) do %>

<% end %>
```

**Comment by DigitalBrains1** [comment]
> With regards to the 80-column thing. That's just a consequence of the style sheet. You could use 4 or 2 space indent for your C-code so that it fits with the style.

Yeah, I suppose that's better here.

> And with regard to image background, I think you can add like a style part to your  tag, I think. At least, I thought that's how you do it in html.

Right, with some search engine results I could quickly deduce a `style` that works better.

Turning off line numbering did not work, with either syntax! Odd.

**Pull request merged**
